# Generated by Django 5.2.12 on 2026-03-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BriefResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ПІБ")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Назва компанії"),
                ),
                (
                    "company_activity",
                    models.CharField(max_length=255, verbose_name="Сфера діяльності"),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("landing", "Лендінг"),
                            ("business_card", "Сайт-візитка"),
                            ("corporate", "Корпоративний сайт"),
                            ("catalog", "Каталог продукції"),
                            ("store", "Інтернет-магазин"),
                        ],
                        max_length=30,
                        verbose_name="Тип проєкту",
                    ),
                ),
                ("project_description", models.TextField(verbose_name="Опис проєкту")),
                ("target_audience", models.TextField(verbose_name="Цільова аудиторія")),
                ("site_goals", models.TextField(verbose_name="Мета сайту")),
                (
                    "required_pages",
                    models.TextField(verbose_name="Потрібні розділи сайту"),
                ),
                (
                    "required_features",
                    models.TextField(verbose_name="Потрібні функції"),
                ),
                (
                    "design_style",
                    models.CharField(
                        choices=[
                            ("minimal", "Мінімалістичний"),
                            ("business", "Діловий"),
                            ("bright", "Яскравий"),
                            ("modern", "Сучасний"),
                        ],
                        max_length=30,
                        verbose_name="Стиль дизайну",
                    ),
                ),
                (
                    "color_preferences",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Побажання щодо кольорів",
                    ),
                ),
                (
                    "content_ready",
                    models.BooleanField(
                        default=False, verbose_name="Чи готовий контент"
                    ),
                ),
                (
                    "deadline",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Терміни"
                    ),
                ),
                (
                    "budget",
                    models.CharField(blank=True, max_length=100, verbose_name="Бюджет"),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="Додаткові побажання"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
            ],
            options={
                "verbose_name": "Відповідь на бриф",
                "verbose_name_plural": "Відповіді на бриф",
                "ordering": ["-created_at"],
            },
        ),
    ]
